[package]
name = "hlist-intersection-assuming-manual-id-assignment"
version = "0.1.0"
edition = "2024"
rust-version = "1.91.0"

[dependencies]
frunk = { version = "0.4.4", default-features = false }
typenum = { version = "1.19.0", default-features = false, features = [ "const-generics"] }
